### ISSUE TITLE
Error on Server and Client Startup - "can't compile world script module!"

### ISSUE THREAD

**Issue by Himself132** [SumrakDZN/Namalsk-Server#6]
Hello,

A recent update to Windows and/or DayZ appears to have broken your modules due to a possible security improvement.  I have three systems with the same error message.

Dayz Server is Experimental exe version DayZServer_x64.exe = 1.17.154.707 on Windows Server 2019 DataCenter 64 bit with build 10.0.17763.  Recently applied update that could be a cause KB5011551.

Dayz Clients are experimental exe version DayZ_x64.exe = 1.17.154.707 on Windows 11 64 bit with build 10.0.22000. Recently applied update that could be a cause KB4023057 and .NET 5.0.15 Security Update for x64 client KB5012416.

Before the updates to the Dayz server and client and these Windows Updates everything was stable and working fine.

Here are the script error log entries, this is reproduceable, basic troubleshooting like rebooting has occurred, disabling the named module allows it to start fine.  Looks like a security mechanism preventing an unsafe call.
_______________________________________________________________________________
Log C:\dayzserver-exp\Namalsk\script_2022-04-07_12-10-46.log started at 07.04. 12:10:46

SCRIPT       : Registered 250 temporary action enum(s), UAN==250
SCRIPT       : ... Backlit Effects Enabled
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\entities\building\military\a2\land_a2_basement_3rd.c,9": Strong ref to 'ScriptedLightBase' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\classes\environment\events\evrstorm\evrstorm.c,52": Strong ref to 'AbstractWave' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\classes\sfx\dynamicmusic.c,9": Strong ref to 'AbstractWave' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\entities\building\military\a2\land_a2_basement_3rd.c,9": Strong ref to 'ScriptedLightBase' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\classes\environment\events\evrstorm\evrstorm.c,52": Strong ref to 'AbstractWave' class is not allowed
SCRIPT    (E): Can't compile "World" script module!
SCRIPT    (E): Failed to load entities script!
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\entities\building\military\a2\land_a2_basement_3rd.c,9": Strong ref to 'ScriptedLightBase' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\classes\environment\events\evrstorm\evrstorm.c,52": Strong ref to 'AbstractWave' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\classes\sfx\dynamicmusic.c,9": Strong ref to 'AbstractWave' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\entities\building\military\a2\land_a2_basement_3rd.c,9": Strong ref to 'ScriptedLightBase' class is not allowed
SCRIPT    (W): @"nst/ns_dayz/scripts/4_World/namalsksurvival\classes\environment\events\evrstorm\evrstorm.c,52": Strong ref to 'AbstractWave' class is not allowed
SCRIPT    (E): Can't compile "World" script module!
SCRIPT    (E): Failed to load entities script!

**Comment by Himself132** [comment]
Just to give you an update since i am looking for a solution to help, rolling back the dayz experimental client allowed the game to load.  Followed the instructions here https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994 and rolled back one version to 1.17.154.672. Server worked on a rollback too

**Comment by SumrakDZN** [comment]
Hello, this is a known issue. Will be resolved with Namalsk update that will release with 1.17 stable update. Thanks for the report.

**Comment by Himself132** [comment]
Hello, what do i do when i want to play experimental dayz server plus namalsk to avoid impacts like this? Should i just delay the experimental client and server updates until you release something to match the version of stable?

**Comment by SumrakDZN** [comment]
This can only be avoided by locally overriding the problematic files. I cant offer any help since there is no experimental branch of Namalsk, only for the stable version of DayZ.

**Comment by Himself132** [comment]
The whole reason I deployed my own private Namalsk on experimental is because I play official/non-experimental on another server.  As you know, if you connect to a new server and start a new character, that old character gets wiped on the other server.  In other words per steam account you can have 2 existing sessions associated with characters/lives.  Unless there is some way for me to have my own private Namalsk server that is on stable but not have that impact another life on another server?  So basically connecting to public official server XYZ with one character and then also having another life going on my own private one and them not impacting each other at all?  I tried to find some information online about how to do this or if it is possible and I see people making additional steam accounts which I’d prefer not to do.
